"""added new column on eccommerce table

Revision ID: 1c239b78be58
Revises: 0672fe820aef
Create Date: 2026-06-29 21:05:32.448647

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "1c239b78be58"
down_revision: Union[str, None] = "0672fe820aef"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "ecommerce_orders",
        sa.Column("tracking_code", sa.String(length=20), nullable=True),
    )
    op.alter_column(
        "ecommerce_orders",
        "calling_status",
        existing_type=postgresql.ENUM(
            "not_called",
            "call1",
            "call2",
            "call3",
            "no_answer",
            "unreachable",
            "confirmed_by_phone",
            "cancelled_by_phone",
            name="calling_status",
        ),
        server_default=None,
        existing_nullable=False,
    )
    op.alter_column(
        "ecommerce_orders",
        "delivery_status",
        existing_type=postgresql.ENUM(
            "not_shipped", "shipped", "delivered", "returned", name="delivery_status"
        ),
        server_default=None,
        existing_nullable=False,
    )
    op.alter_column(
        "ecommerce_orders",
        "is_hidden_from_livreurs",
        existing_type=sa.BOOLEAN(),
        server_default=None,
        existing_nullable=False,
    )
    op.create_index(
        op.f("ix_ecommerce_orders_tracking_code"),
        "ecommerce_orders",
        ["tracking_code"],
        unique=True,
    )
    op.alter_column(
        "store_users",
        "is_active",
        existing_type=sa.BOOLEAN(),
        server_default=None,
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "store_users",
        "is_active",
        existing_type=sa.BOOLEAN(),
        server_default=sa.text("true"),
        existing_nullable=False,
    )
    op.drop_index(
        op.f("ix_ecommerce_orders_tracking_code"), table_name="ecommerce_orders"
    )
    op.alter_column(
        "ecommerce_orders",
        "is_hidden_from_livreurs",
        existing_type=sa.BOOLEAN(),
        server_default=sa.text("false"),
        existing_nullable=False,
    )
    op.alter_column(
        "ecommerce_orders",
        "delivery_status",
        existing_type=postgresql.ENUM(
            "not_shipped", "shipped", "delivered", "returned", name="delivery_status"
        ),
        server_default=sa.text("'not_shipped'::delivery_status"),
        existing_nullable=False,
    )
    op.alter_column(
        "ecommerce_orders",
        "calling_status",
        existing_type=postgresql.ENUM(
            "not_called",
            "call1",
            "call2",
            "call3",
            "no_answer",
            "unreachable",
            "confirmed_by_phone",
            "cancelled_by_phone",
            name="calling_status",
        ),
        server_default=sa.text("'not_called'::calling_status"),
        existing_nullable=False,
    )
    op.drop_column("ecommerce_orders", "tracking_code")
    # ### end Alembic commands ###
