"""add ecommerce_orders table v2

Revision ID: 2c078a7fc1ed
Revises: 843303a61948
Create Date: 2026-06-24 19:31:08.161021

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "2c078a7fc1ed"
down_revision: Union[str, None] = "843303a61948"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "ecommerce_orders",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("full_name", sa.String(length=150), nullable=False),
        sa.Column("phone_number", sa.String(length=20), nullable=False),
        sa.Column("wilaya_id", sa.Integer(), nullable=False),
        sa.Column("wilaya_name", sa.String(length=100), nullable=False),
        sa.Column("baladia_id", sa.Integer(), nullable=False),
        sa.Column("baladia_name", sa.String(length=100), nullable=False),
        sa.Column("address_details", sa.String(length=500), nullable=True),
        sa.Column("product_id", sa.Integer(), nullable=False),
        sa.Column("product_name_snapshot", sa.String(length=300), nullable=False),
        sa.Column(
            "unit_price_snapshot", sa.Numeric(precision=10, scale=2), nullable=False
        ),
        sa.Column("quantity", sa.Integer(), nullable=False),
        sa.Column("selected_variants", sa.Text(), nullable=True),
        sa.Column("total_price", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("notes", sa.String(length=500), nullable=True),
        sa.Column("telegram_notified", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["products.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_ecommerce_orders_id"), "ecommerce_orders", ["id"], unique=False
    )
    op.create_index(
        op.f("ix_ecommerce_orders_phone_number"),
        "ecommerce_orders",
        ["phone_number"],
        unique=False,
    )
    op.create_index(
        op.f("ix_ecommerce_orders_product_id"),
        "ecommerce_orders",
        ["product_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_ecommerce_orders_status"), "ecommerce_orders", ["status"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_ecommerce_orders_status"), table_name="ecommerce_orders")
    op.drop_index(op.f("ix_ecommerce_orders_product_id"), table_name="ecommerce_orders")
    op.drop_index(
        op.f("ix_ecommerce_orders_phone_number"), table_name="ecommerce_orders"
    )
    op.drop_index(op.f("ix_ecommerce_orders_id"), table_name="ecommerce_orders")
    op.drop_table("ecommerce_orders")
    # ### end Alembic commands ###
