"""add landing_blocks column to product

Revision ID: 5bf1fdaf1a2e
Revises: 2c078a7fc1ed
Create Date: 2026-06-25 13:55:48.280982

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5bf1fdaf1a2e'
down_revision: Union[str, None] = '2c078a7fc1ed'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('landing_blocks', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'landing_blocks')
    # ### end Alembic commands ###
