"""add is_sold column to products

Revision ID: 667ca2e269f4
Revises: 8e58004247ae
Create Date: 2025-12-20 22:38:58.668366

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '667ca2e269f4'
down_revision: Union[str, None] = '8e58004247ae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('is_sold', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'is_sold')
    # ### end Alembic commands ###
