"""add variants column on item bill  table 

Revision ID: 7508233cb54d
Revises: 9c83f3dbf124
Create Date: 2025-12-26 12:22:27.032065

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7508233cb54d'
down_revision: Union[str, None] = '9c83f3dbf124'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bills', sa.Column('selected_variants', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bills', 'selected_variants')
    # ### end Alembic commands ###
