"""add variants column on item bill  table v2 

Revision ID: 9b117f52b533
Revises: 7508233cb54d
Create Date: 2025-12-26 12:32:13.090210

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9b117f52b533'
down_revision: Union[str, None] = '7508233cb54d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bill_items', sa.Column('selected_variants', sa.Text(), nullable=True))
    op.drop_column('bills', 'selected_variants')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bills', sa.Column('selected_variants', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_column('bill_items', 'selected_variants')
    # ### end Alembic commands ###
