"""add variants column on product table 

Revision ID: 9c83f3dbf124
Revises: a19aa6822c40
Create Date: 2025-12-25 16:01:41.667694

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9c83f3dbf124'
down_revision: Union[str, None] = 'a19aa6822c40'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('variants', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'variants')
    # ### end Alembic commands ###
