"""add new column on the bill table named delivery_status

Revision ID: a19aa6822c40
Revises: e06199e65269
Create Date: 2025-12-24 13:40:00.238869

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a19aa6822c40'
down_revision: Union[str, None] = 'e06199e65269'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bills', sa.Column('delivery_status',
                  sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bills', 'delivery_status')
    # ### end Alembic commands ###
