"""add new model named client account 

Revision ID: e06199e65269
Revises: 667ca2e269f4
Create Date: 2025-12-23 12:59:05.227997

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e06199e65269'
down_revision: Union[str, None] = '667ca2e269f4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('client_accounts',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('client_id', sa.Integer(), nullable=False),
                    sa.Column('total_amount', sa.Numeric(
                        precision=10, scale=2), nullable=False),
                    sa.Column('total_paid', sa.Numeric(
                        precision=10, scale=2), nullable=False),
                    sa.Column('total_remaining', sa.Numeric(
                        precision=10, scale=2), nullable=False),
                    sa.Column('total_credit', sa.Numeric(
                        precision=10, scale=2), nullable=False),
                    sa.Column('created_at', sa.DateTime(timezone=True),
                              server_default=sa.text('now()'), nullable=True),
                    sa.Column('updated_at', sa.DateTime(
                        timezone=True), nullable=True),
                    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('client_id')
                    )
    op.create_index(op.f('ix_client_accounts_id'),
                    'client_accounts', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_client_accounts_id'), table_name='client_accounts')
    op.drop_table('client_accounts')
    # ### end Alembic commands ###
